"l2"= 185
"D3@Body Driving Dimensions" = "l2"
"l1"= 85
"D4@Body Driving Dimensions" = "l1"
"s1r"= 2.14212rad
"s2r"= - 2rad
"offset"= 15mm
"s1_len"= 0.08255m
"s2_len"= 0.015m
"s1_anchor_dist"= "offset" + "l1" + "s1_len"
"s2_anchor_dist"= "offset" + "l1" + "s2_len"'this was: = "offset" + "l1" + "s2_len"
"D5@Body Driving Dimensions" = "s1_anchor_dist"
"D6@Body Driving Dimensions" = "s2_anchor_dist"
"D7@Body Driving Dimensions" = "s1r"
"D8@Body Driving Dimensions" =  - "s2r"
"carbon_fiber_plate_thickness"=6
"D1@Tibya" = "carbon_fiber_plate_thickness"
"D1@Boss-Extrude2"="carbon_fiber_plate_thickness"
"motor_to_motor_spacing"=55.5
"D1@Sketch4"="motor_to_motor_spacing"
"D1@Boss-Extrude3"="l1"+"l2" + 8
"D1" = "motor_to_motor_spacing" + 30mm
"D1@Boss-Extrude12"="carbon_fiber_plate_thickness"
"D3@Sketch44"="s2_anchor_dist"/2
